input='/home/lzephyr/TADMaster/jobs/normTest/input/uij.chr19';
res='40000';
output='/home/lzephyr/TADMaster/jobs/normTest';
chr='19';
spectral=1;
armatus=0;
armatus_gamma=.2;
di=0;
di_length=10;
disp(armatus_gamma)
TAD_methods;
